/**
 * GitHub OAuth: authorization URL and token exchange.
 * Uses GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET, and GITHUB_CALLBACK_URL from env.
 */

const GITHUB_AUTH_URL = "https://github.com/login/oauth/authorize";
const GITHUB_TOKEN_URL = "https://github.com/login/oauth/access_token";
const SCOPES = ["repo", "read:user"].join(" ");

/** True when Client ID, secret, and callback URL are all non-empty (whitespace-trimmed). */
export function isGitHubOAuthConfigured(): boolean {
  const id = process.env.GITHUB_CLIENT_ID?.trim();
  const secret = process.env.GITHUB_CLIENT_SECRET?.trim();
  const callback = process.env.GITHUB_CALLBACK_URL?.trim();
  return Boolean(id && secret && callback);
}

/**
 * Returns the GitHub OAuth authorization URL to redirect the user to.
 * State should be generated by the caller and validated in callback.
 */
export function getAuthorizationUrl(state?: string): string {
  const clientId = process.env.GITHUB_CLIENT_ID;
  if (!clientId) {
    throw new Error("GITHUB_CLIENT_ID is not set");
  }
  const params = new URLSearchParams({
    client_id: clientId,
    scope: SCOPES,
    redirect_uri: getCallbackUrl(),
  });
  if (state) params.set("state", state);
  return `${GITHUB_AUTH_URL}?${params.toString()}`;
}

/**
 * Exchanges an OAuth code for an access token.
 * @param code - The code from the callback query
 * @returns Access token
 */
export async function exchangeCodeForToken(code: string): Promise<string> {
  const clientId = process.env.GITHUB_CLIENT_ID;
  const clientSecret = process.env.GITHUB_CLIENT_SECRET;
  if (!clientId || !clientSecret) {
    throw new Error("GITHUB_CLIENT_ID or GITHUB_CLIENT_SECRET is not set");
  }

  const res = await fetch(GITHUB_TOKEN_URL, {
    method: "POST",
    headers: {
      Accept: "application/json",
      "Content-Type": "application/json",
    },
    body: JSON.stringify({
      client_id: clientId,
      client_secret: clientSecret,
      code,
      redirect_uri: getCallbackUrl(),
    }),
  });

  if (!res.ok) {
    const text = await res.text();
    throw new Error(`GitHub token exchange failed: ${res.status} ${text}`);
  }

  const data = (await res.json()) as { access_token?: string; error?: string };
  if (data.error) {
    throw new Error(`GitHub OAuth error: ${data.error}`);
  }
  if (!data.access_token) {
    throw new Error("GitHub did not return an access token");
  }
  return data.access_token;
}

function getCallbackUrl(): string {
  const url = process.env.GITHUB_CALLBACK_URL;
  if (!url) {
    throw new Error("GITHUB_CALLBACK_URL is not set");
  }
  return url;
}
