/**
 * AI Engine — LLM orchestration and content generation.
 * Public API for this module. See README.md for scope and dependencies.
 * Context: { source: 'idea' | 'repo', projectName?, codebaseSummary? } for prompt tailoring.
 */

import { logger } from "../../logger/index.js";
import { complete } from "./providers/index.js";
import { buildPRDPrompt } from "./prompts/prd.js";
import { buildUserStoriesPrompt } from "./prompts/user-stories.js";
import { buildUserJourneysPrompt } from "./prompts/user-journeys.js";

export async function generatePRD(
  input: string,
  context?: Record<string, unknown>
): Promise<string> {
  const { system, user } = buildPRDPrompt(input, context);
  logger.debug("PRD generation", {
    promptId: "prd",
    model: process.env.OPENROUTER_MODEL ?? "default",
  });
  return complete(user, { systemPrompt: system });
}

export async function generateUserStories(
  input: string,
  context?: Record<string, unknown>
): Promise<string> {
  const { system, user } = buildUserStoriesPrompt(input, context);
  logger.debug("User stories generation", {
    promptId: "user-stories",
    model: process.env.OPENROUTER_MODEL ?? "default",
  });
  return complete(user, { systemPrompt: system });
}

export async function generateUserJourneys(
  input: string,
  context?: Record<string, unknown>
): Promise<string> {
  const { system, user } = buildUserJourneysPrompt(input, context);
  logger.debug("User journeys generation", {
    promptId: "user-journeys",
    model: process.env.OPENROUTER_MODEL ?? "default",
  });
  return complete(user, { systemPrompt: system });
}

export async function generateApiDocs(
  input: string,
  _context?: Record<string, unknown>
): Promise<string> {
  // TODO: Integrate LLM
  return `# API Documentation\n\n${input}\n\n*Generated by DevDocs AI*`;
}

export { embed, embedBatch } from "./providers/index.js";
export { complete, type CompleteOptions } from "./providers/index.js";
