/**
 * AI Engine — LLM orchestration and content generation.
 * Public API for this module. See README.md for scope and dependencies.
 * Context: { source: 'idea' | 'repo', projectName?, codebaseSummary? } for prompt tailoring.
 */

import { buildPRDPrompt } from "./prompts/prd.js";
import { buildUserStoriesPrompt } from "./prompts/user-stories.js";
import { buildUserJourneysPrompt } from "./prompts/user-journeys.js";

export async function generatePRD(
  input: string,
  context?: Record<string, unknown>
): Promise<string> {
  // TODO: Integrate OpenRouter/GPT-4; for now return structured output from input
  buildPRDPrompt(input, context); // ensures prompt shape is used when LLM is wired
  return `# Product Requirements Document\n\n${input}\n\n*Generated by DevDocs AI*`;
}

export async function generateUserStories(
  input: string,
  context?: Record<string, unknown>
): Promise<string> {
  buildUserStoriesPrompt(input, context);
  return `## User Stories\n\n${input}\n\n*Generated by DevDocs AI*`;
}

export async function generateUserJourneys(
  input: string,
  context?: Record<string, unknown>
): Promise<string> {
  buildUserJourneysPrompt(input, context);
  return `## User Journeys\n\n${input}\n\n*Generated by DevDocs AI*`;
}

export async function generateApiDocs(
  input: string,
  _context?: Record<string, unknown>
): Promise<string> {
  // TODO: Integrate LLM
  return `# API Documentation\n\n${input}\n\n*Generated by DevDocs AI*`;
}
